Repository atom/atom, pull requests merged in 2018-03, with the labels that each got.

#16812 Add additional dependencies for linux
  resources/linux/debian/control.in
Labels: needs-review, needs-testing

#16884 Randomize fontSize and lineHeight in the random test
  spec/text-editor-component-spec.js
Labels: needs-review

#16886 Fix shaking editor when typing
  src/text-editor-component.js
Labels: needs-review

#16918 Weekly Focus: 2018-03-12
  docs/focus/2018-03-12.md
  docs/focus/README.md
Labels: weekly-focus
