Repository atom/atom, pull requests merged in 2018-08, with the labels that each got.

#17803 Use npm and apm ci in CI builds
  .travis.yml
  appveyor.yml
  script/bootstrap
  script/build
  script/config.js
  script/lib/install-apm.js
  script/lib/install-script-dependencies.js
  script/lib/run-apm-install.js
  script/package-lock.json
  script/vsts/platforms/linux.yml
  script/vsts/platforms/macos.yml
  script/vsts/platforms/windows.yml
Labels: work-in-progress

#17886 Allow nightly releases to auto-update
  src/main-process/auto-update-manager.coffee
Labels: :night_with_stars: nightly-releases

#17795 Atom from WSL respects windows drive mount location defined in /etc/wsl.conf
  resources/win/atom.sh
Labels: needs-testing

#11139 Add Selection.onDidChangeRange event object to emitter
  spec/selection-spec.js
  src/selection.js
Labels: needs-review
