Repository atom/atom, pull requests merged in 2019-02, with the labels that each got.

#18759 RFC: Block decoration ordering
  docs/rfcs/004-decoration-ordering.md
Labels: RFC

#18788 Use a custom Jasmine reporter to actually show spec names
  .travis.yml
  appveyor.yml
  script/vsts/platforms/linux.yml
  script/vsts/platforms/macos.yml
  script/vsts/platforms/windows.yml
  spec/jasmine-list-reporter.js
  spec/jasmine-test-runner.coffee
Labels: work-in-progress

#17529 File -> Open works without open windows
  spec/main-process/atom-application.test.js
  src/main-process/atom-application.js
Labels: needs-review, needs-testing

#18855 Fix "Open Folder" menu item on Windows
  spec/main-process/atom-application.test.js
  src/main-process/atom-application.js
Labels: regression

#18802 Report test result metadata to Azure DevOps
  script/package-lock.json
  script/package.json
  script/postprocess-junit-results
  script/postprocess-junit-results.cmd
  script/test
  script/vsts/platforms/linux.yml
  script/vsts/platforms/macos.yml
  script/vsts/platforms/windows.yml
  spec/jasmine-junit-reporter.js
  spec/jasmine-test-runner.coffee
Labels: work-in-progress

#18863 Allow the use of console, stdout, and stderr in Jasmine tests
  src/initialize-test-window.coffee
Labels: work-in-progress

#16558 Add async implementation of GitRepositoryProvider.repositoryForDirectory
  spec/git-repository-provider-spec.js
  src/git-repository-provider.coffee
  src/git-repository-provider.js
Labels: needs-review
