Repository atom/atom, pull requests merged in 2020-11, with the labels that each got.

#21578 ⬆️ postcss@8.1.4
  package-lock.json
  package.json
Labels: depency ⬆️

#21562 Use capture true instead of boolean in addEventListener
  src/atom-environment.js
  src/command-registry.js
  src/initialize-benchmark-window.js
  src/initialize-test-window.coffee
  src/pane-element.js
  src/tooltip.js
  src/workspace-element.js
Labels: triaged

#21641 ⬆️ electron-osx-sign@0.5.0
  package-lock.json
  package.json
Labels: depency ⬆️

#21665 ⬆️ postcss@8.1.6
  package-lock.json
  package.json
Labels: depency ⬆️

#21318 Update the macOS Azure CI image to macos-10.15
  script/vsts/nightly-release.yml
  script/vsts/platforms/macos.yml
Labels: under-review
