Repository atom/atom, pull requests merged in 2020-10, with the labels that each got.

#21418 ⬆️ find-and-replace@0.219.6
  package-lock.json
  package.json
Labels: depency ⬆️

#21419 ⬆️ settings-view@0.261.6
  package-lock.json
  package.json
Labels: depency ⬆️

#21425 Update Debian dependencies, fixes Ubuntu Groovy
  resources/linux/debian/control.in
Labels: triaged

#21231 ⬆️ mocha@6.2.3
  package-lock.json
  package.json
Labels: depency ⬆️

#21437 ⬆️ focus-trap@6.1.2
  package-lock.json
  package.json
Labels: depency ⬆️

#21444 ⬆️ sinon@9.2.0
  package-lock.json
  package.json
Labels: depency ⬆️

#21354 Remove electron configuration
  script/build
  script/lib/install-script-dependencies.js
  script/lib/run-apm-install.js
Labels: under-review

#21413 script/bootstrap: Make `apm --version` print the Atom version currently being bootstrapped
  script/bootstrap
Labels: triaged

#21453 ⬆️ focus-trap@6.1.3
  package-lock.json
  package.json
Labels: depency ⬆️

#21470 ⬆️ color@3.1.3
  package-lock.json
  package.json
Labels: depency ⬆️

#21387 ⬆️ postcss-selector-parser@6.0.4
  package-lock.json
  package.json
  script/lib/generate-startup-snapshot.js
  src/style-manager.js
Labels: depency ⬆️

#21491 ⬆️ normalize-package-data@3.0.0
  package-lock.json
  package.json
Labels: depency ⬆️

#21518 ⬆️ yargs@16.1.0
  package-lock.json
  package.json
Labels: depency ⬆️

#21492 ⬆️ tree-sitter@0.17.1
  package-lock.json
  package.json
Labels: depency ⬆️

#20892 Use HTML native preventScroll for textEditorComponent focus
  src/text-editor-component.js
Labels: triaged

#21543 ⬆️ postcss@8.1.2
  package-lock.json
  package.json
Labels: depency ⬆️

#21542 ⬆️ chart.js@2.9.4
  package-lock.json
  package.json
Labels: depency ⬆️

#20393 Skip shell functions when parsing env
  src/update-process-env.js
Labels: more-information-needed, triaged, under-review

#21544 ⬆️ resolve@1.18.1
  package-lock.json
  package.json
Labels: depency ⬆️

#21565 ⬆️ postcss@8.1.2
  package-lock.json
  package.json
Labels: depency ⬆️

#21566 ⬆️ resolve@1.18.1
  package-lock.json
  package.json
Labels: depency ⬆️

#21563 ⬆️ chart.js@2.9.4
  package-lock.json
  package.json
Labels: depency ⬆️

#21573 ⬆️ spell-check@0.76.2
  package-lock.json
  package.json
Labels: depency ⬆️

#21572 ⬆️ postcss@8.1.3
  package-lock.json
  package.json
Labels: depency ⬆️

#21589 ⬆️ temp@0.9.2
  package-lock.json
  package.json
Labels: depency ⬆️

#21587 Fixed atom.confirm and internal use of dialog.showMessageBox
  src/application-delegate.js
  src/main-process/atom-application.js
  src/main-process/atom-window.js
  src/main-process/auto-update-manager.js
  src/main-process/file-recovery-service.js
Labels: triaged, under-review

#21604 ⬆️ sinon@9.2.1
  package-lock.json
  package.json
Labels: depency ⬆️

#21615 ⬆️ tree-view@0.228.2
  package-lock.json
  package.json
Labels: depency ⬆️

#21490 CI: Get 32-bit Node via the official NodeTool task
  script/vsts/platforms/templates/bootstrap.yml
  script/vsts/platforms/templates/build.yml
  script/vsts/platforms/templates/preparation.yml
  script/vsts/platforms/templates/test.yml
  script/vsts/platforms/windows.yml
  script/vsts/windows-run.js
Labels: under-review

#21595 ⬆️ focus-trap@6.1.4
  package-lock.json
  package.json
Labels: depency ⬆️

#21579 ⬆️ prebuild-install@6.0.0
  package-lock.json
  package.json
Labels: depency ⬆️
