Repository atom/atom, pull requests merged in 2020-09, with the labels that each got.

#21248 ⬆️ language-php@0.44.7
  package-lock.json
  package.json
Labels: depency ⬆️

#21234 Allow Title Bar to be Hidden (closes #13249)
  spec/main-process/atom-window.test.js
  src/config-schema.js
  src/main-process/atom-window.js
Labels: under-review

#21282 ⬆️ vscode-ripgrep@1.9.0
  package-lock.json
  package.json
Labels: depency ⬆️

#21086 ⬆️ marked@1.1.1
  package-lock.json
  package.json
Labels: depency ⬆️

#20956 ⬆️ github@0.35.0
  package-lock.json
  package.json
Labels: depency ⬆️

#21028 ⬆️ electron-osx-sign@0.4.17
  package-lock.json
  package.json
Labels: depency ⬆️

#21029 ⬆️ etch@0.14.0
  package-lock.json
  package.json
Labels: depency ⬆️

#20976 ⬆️ electron-notarize@1.0.0
  package-lock.json
  package.json
Labels: depency ⬆️

#21062 remove redundant CS require
  script/build
Labels: under-review

#21193 ⬆️ fs-admin@0.15.0
  package-lock.json
  package.json
Labels: depency ⬆️

#20975 ⬆️ devtron@1.4.0
  package-lock.json
  package.json
Labels: depency ⬆️

#21310 ⬆️ tree-view@0.228.1
  package-lock.json
  package.json
Labels: depency ⬆️

#21109 Parallelize Tests in CI (+ Refactor and Improvements)
  script/test
  script/vsts/nightly-release.yml
  script/vsts/platforms/macos.yml
  script/vsts/platforms/templates/test.yml
  script/vsts/platforms/windows.yml
  script/vsts/release-branch-build.yml
  src/main-process/start.js
Labels: under-review

#21319 ⬆️ postcss@8.0.3
  package-lock.json
  package.json
Labels: depency ⬆️

#21331 ⬆️ postcss@8.0.5
  package-lock.json
  package.json
Labels: depency ⬆️

#21046 ⬆️ typescript-simple@8.0.6
  package-lock.json
  package.json
Labels: depency ⬆️

#21338 ⬆️ tree-sitter@0.16.2
  package-lock.json
  package.json
Labels: depency ⬆️

#21295 Tests: retry timed out steps automatically
  script/test
Labels: under-review

#21036 ⬆️ mocha-junit-reporter@2.0.0
  package-lock.json
  package.json
Labels: depency ⬆️

#21366 ⬆️ fuzzy-finder@1.14.3
  package-lock.json
  package.json
Labels: depency ⬆️

#21256 ⬆️ focus-trap@6.0.1
  package-lock.json
  package.json
  src/panel-container-element.js
Labels: blocked, depency ⬆️

#21364 ⬆️ postcss@8.0.8
  package-lock.json
  package.json
Labels: depency ⬆️

#21376 ⬆️ postcss@8.0.9
  package-lock.json
  package.json
Labels: depency ⬆️

#21374 ⬆️ etch@0.14.1
  package-lock.json
  package.json
Labels: depency ⬆️

#21377 ⬆️ tree-sitter@0.17.0
  package-lock.json
  package.json
Labels: depency ⬆️

#21391 ⬆️ postcss@8.1.0
  package-lock.json
  package.json
Labels: depency ⬆️

#21406 ⬆️ postcss@8.1.1
  package-lock.json
  package.json
Labels: depency ⬆️

#21411 ⬆️ sinon@9.1.0
  package-lock.json
  package.json
Labels: depency ⬆️

#21405 ⬆️ marked@1.2.0
  package-lock.json
  package.json
Labels: depency ⬆️
