Repository atom/atom, pull requests merged in 2021-05, with the labels that each got.

#22315 Replaced OS X Yosemite-era icon with macOS Big Sur icon for Atom for Macs
  resources/app-icons/beta/atom.icns
  resources/app-icons/dev/atom.icns
  resources/app-icons/nightly/atom.icns
  resources/app-icons/stable/atom.icns
Labels: triaged

#22123 Fix app icons on Windows
  resources/app-icons/beta/atom.ico
  resources/app-icons/dev/atom.ico
  resources/app-icons/nightly/atom.ico
  resources/app-icons/stable/atom.ico
Labels: triaged

#22103 Convert var to const/let in src files
  src/babel.js
  src/coffee-script.js
  src/compile-cache.js
  src/delegated-listener.js
  src/history-manager.js
  src/module-cache.js
  src/package-manager.js
  src/package.js
  src/state-store.js
  src/style-manager.js
  src/text-editor-component.js
  src/text-editor-registry.js
  src/text-mate-language-mode.js
  src/tooltip.js
  src/typescript.js
  src/view-registry.js
Labels: triaged

#11786 fix spec toShow()
  spec/spec-helper.coffee
Labels: needs-testing

#18321 Implementing tree-sitter based indentation logic
  spec/fixtures/indentation/classes.js
  spec/fixtures/indentation/expressions.js
  spec/fixtures/indentation/function_call.js
  spec/fixtures/indentation/if_then_else.js
  spec/fixtures/indentation/jsx.jsx
  spec/fixtures/indentation/objects_and_array.js
  spec/fixtures/indentation/switch.js
  spec/fixtures/indentation/while.js
  spec/tree-indenter-spec.js
  src/tree-indenter.js
  src/tree-sitter-language-mode.js
Labels: needs-review, triaged
