Repository atom/atom, pull requests merged in 2021-09, with the labels that each got.

#15975 Add custom start tiles
  resources/win/atom.visualElementsManifest.xml
  resources/win/visualElements/Square150x150Logo.scale-100.png
  resources/win/visualElements/Square150x150Logo.scale-125.png
  resources/win/visualElements/Square150x150Logo.scale-150.png
  resources/win/visualElements/Square150x150Logo.scale-200.png
  resources/win/visualElements/Square150x150Logo.scale-400.png
  resources/win/visualElements/Square44x44Logo.scale-100.png
  resources/win/visualElements/Square44x44Logo.scale-125.png
  resources/win/visualElements/Square44x44Logo.scale-150.png
  resources/win/visualElements/Square44x44Logo.scale-200.png
  resources/win/visualElements/Square44x44Logo.scale-400.png
  resources/win/visualElements/Square71x71Logo.scale-100.png
  resources/win/visualElements/Square71x71Logo.scale-125.png
  resources/win/visualElements/Square71x71Logo.scale-150.png
  resources/win/visualElements/Square71x71Logo.scale-200.png
  resources/win/visualElements/Square71x71Logo.scale-400.png
Labels: windows, needs-review

#17107 Convert arguments to absolute paths
  resources/win/atom.sh
Labels: windows

#17681 RFC: Pre-transpile apm packages
  docs/rfcs/005-pretranspile.md
Labels: RFC

#17628 Fix getEnvFromShell() to correctly handle newlines in env vars
  spec/update-process-env-spec.js
  src/update-process-env.js
Labels: needs-testing

#22952 Remove deprecated code strings
  packages/one-dark-ui/lib/main.js
  packages/one-light-ui/lib/main.js
  src/main-process/atom-application.js
  vendor/jasmine.js
Labels: needs-review
